### PR TITLE
Amadeo Bee wants to join the party!

### PR DESCRIPTION
**Pull request by amadeobr**
please let me in!!

### CODE REVIEW

**Comment by amadeobr** [comment]
thanks!

**Comment by amadeobr** [comment]
hahahaha

**Comment by amadeobr** [comment]
this is great

**Comment by amadeobr** [comment]
hey barbara look at the screen

**Comment by amadeobr** [comment]
jessica keep listening!

**Comment by PeterBell** [comment]
colbert

**Comment by amadeobr** [comment]
high five!

**Comment by amadeobr** [comment]
Awesome :)

**Pull request merged**
